import './globals.css'
import type { Metadata } from 'next'
import { Inter, Quattrocento, Quattrocento_Sans } from 'next/font/google'
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })
const quattrocento = Quattrocento({weight: "400", subsets: ['latin'], variable: "--font-quattrocento"})
const quattrocentoSans = Quattrocento_Sans({ weight: "400", subsets: ['latin'], variable: "--font-quattrocento-sans" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${quattrocento.variable} ${quattrocentoSans.variable} bg-[#f5f5f5] font-quattrocento-sans`}>
        {/* <Navbar /> */}
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
